version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 8
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 25
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    config:
      threshold: 6
  return-statements:
    config:
      threshold: 6
  similar-code:
    enabled: false
  identical-code:
    enabled: false

exclude_patterns:
- ".github/"
- "**/config/"
- "**/css/"
- "**/images/"
- "**/js/"
- "**/tests/"
- "**/*.yml"
- "**/*.yaml"
- "**/*.md"
- "**/*.xml"
- "**/*.txt"
- "composer.json"
- "composer.lock"
- ".gitignore"
- "Dockerfile"
