version: "2"

checks:
  argument-count:
    enabled: false
    config:
      threshold: 8
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: false
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 25
  method-count:
    enabled: false
    config:
      threshold: 20
  method-lines:
    enabled: false
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 6
  return-statements:
    enabled: true
    config:
      threshold: 6
  similar-code:
    enabled: false
  identical-code:
    enabled: false

exclude_patterns:
- "**/config/"
- "**/css/"
- "**/js/jquery-*.js",
- "**/images/"
- "**/tests/"
- "**/docs/"
- "**/*.yml"
- "**/*.yaml"
- "**/*.md"
- "**/*.xml"
- "**/*.txt"
- "composer.json"
- "composer.lock"
- ".gitignore"
- "Dockerfile"
- ".github/"
