name: PHPUnit
on:
  push:
    branches:
      - 2.x
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run Automated testing
        uses: tripal/test-tripal-action@v1.5
        with:
          directory-name: 'tripal_blast'
          modules: 'tripal_blast'
          php-version: '8.1'
          pgsql-version: '16'
          drupal-version: '10.0.x-dev'
