site_name: Tripal BLAST Documentation
site_url: https://tripal.github.io/tripal_blast
site_author: Lacey-Anne Sanderson
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes – searchable, customizable, in 60+ languages, for all devices

# Repository
repo_name: tripal/tripal_blast
repo_url: https://github.com/tripal/tripal_blast

# Copyright
copyright: Copyright &copy; 2018 - 2024, Lacey-Anne Sanderson, University of Saskatchewan

nav:
  - Home: index.md
  - Installation:
    - Adding to an existing site: install/composer-install.md
    - Demonstration via Docker: install/docker-demo.md
  - Guiding your Users:
    - Submitting a BLAST request: users/submit-blast.md
    - Finding previous requests: users/previous-requests.md
    - BLAST result page: users/result-page.md
  - Site Administration:
    - Configuring BLAST: admin/config.md
    - Managing BLAST databases: admin/blast-databases.md
    - Running jobs automatically: admin/running-jobs.md
  # - Customization:
  #   - Custom Link-outs
  #   - Custom Styling

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  logo: images/TripalLogo_only.png
  favicon: images/TripalLogo_only.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
